# Generated by Django 5.2.8 on 2025-12-15 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('student_name', models.CharField(max_length=150)),
                ('student_email', models.EmailField(max_length=254)),
                ('father_name', models.CharField(max_length=150)),
                ('mother_name', models.CharField(max_length=150)),
                ('father_phone', models.CharField(max_length=20)),
                ('mother_phone', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('address', models.TextField(default='Not Provided')),
                ('extra_details', models.JSONField(blank=True, default=dict)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.section')),
            ],
        ),
    ]
