# Generated by Django 5.2.8 on 2026-01-14 10:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_of_admission',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
