# Generated by Django 5.2.8 on 2026-01-19 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0003_student_date_of_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.standard'),
        ),
    ]
