# Generated by Django 5.2.8 on 2026-03-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='accommodation',
            field=models.CharField(blank=True, choices=[('day_scholar', 'Day Scholar'), ('hosteller', 'Hosteller')], max_length=20, null=True),
        ),
    ]
