# Generated by Django 5.2.8 on 2026-06-18 11:33

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_enrollment_school_student_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='role_permissions',
            field=models.JSONField(blank=True, default=students.models.default_student_role_permissions),
        ),
    ]
