# Generated by Django 5.2.8 on 2026-06-18 11:57

import django.db.models.deletion
import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_school_logo'),
        ('students', '0009_student_role_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_permissions', models.JSONField(blank=True, default=students.models.default_student_role_permissions)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_role_permission', to='school.school')),
            ],
        ),
    ]
