# Generated by Django 5.2.8 on 2026-06-18 13:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_school_scoped_academics'),
        ('school', '0006_school_scoped_academics'),
        ('students', '0010_school_student_role_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('school', 'student_id'), name='unique_student_id_per_school'),
        ),
    ]
