# Generated by Django 5.2.8 on 2026-01-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('applicable_for', models.CharField(choices=[('everyone', 'Everyone (School Closed)'), ('students_only', 'Students Only'), ('staff_only', 'Staff Only')], default='everyone', max_length=20)),
            ],
        ),
    ]
