# Generated by Django 5.2.8 on 2026-02-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='applicable_for',
            field=models.CharField(choices=[('everyone', 'Everyone (School Closed)'), ('students_only', 'Students Only'), ('staff', 'Non-Teaching Staff Only'), ('teachers', 'Teachers Only')], default='everyone', max_length=20),
        ),
    ]
