# Generated by Django 5.2.8 on 2026-01-06 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nonteachingstaff',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nonteachingstaff',
            name='role',
            field=models.CharField(choices=[('admin_staff', 'Admin Staff'), ('finance_staff', 'Finance Staff'), ('it_staff', 'IT Staff'), ('operations_staff', 'Operations Staff'), ('transport_staff', 'Transport Staff'), ('external_staff', 'External Staff')], max_length=50),
        ),
    ]
