# Generated by Django 5.2.8 on 2026-02-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_nonteachingstaff_user_alter_nonteachingstaff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonteachingstaff',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
