# Generated by Django 5.2.8 on 2026-03-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_nonteachingstaff_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonteachingstaff',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/staff/'),
        ),
    ]
