# Generated by Django 5.2.8 on 2026-03-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_alter_nonteachingstaff_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonteachingstaff',
            name='role',
            field=models.CharField(choices=[('admin_staff', 'Admin Staff'), ('finance_staff', 'Finance Staff'), ('it_staff', 'IT Staff'), ('operations_staff', 'Operations Staff'), ('hostel_warden', 'Hostel Warden'), ('transport_staff', 'Transport Staff'), ('external_staff', 'External Staff')], max_length=50),
        ),
    ]
