# Generated by Django 5.2.8 on 2026-06-13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_alter_nonteachingstaff_role'),
    ]

    operations = []
