# Generated by Django 5.2.8 on 2026-06-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_institution_alter_school_options_academicyear_school_and_more'),
        ('staff', '0008_compatibility_placeholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonteachingstaff',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='school.school'),
        ),
    ]
