# Generated by Django 5.2.8 on 2026-06-18 12:03

import django.db.models.deletion
import staff.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_school_logo'),
        ('staff', '0009_nonteachingstaff_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin_staff', 'Admin Staff'), ('finance_staff', 'Finance Staff'), ('it_staff', 'IT Staff'), ('operations_staff', 'Operations Staff'), ('hostel_warden', 'Hostel Warden'), ('transport_staff', 'Transport Staff'), ('external_staff', 'External Staff')], max_length=50)),
                ('role_permissions', models.JSONField(blank=True, default=staff.models.default_staff_role_permissions)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_role_permissions', to='school.school')),
            ],
            options={
                'ordering': ['role'],
                'unique_together': {('school', 'role')},
            },
        ),
    ]
