# Generated by Django 5.2.8 on 2026-06-18 13:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_school_scoped_academics'),
        ('staff', '0010_staff_role_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonteachingstaff',
            name='staff_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='nonteachingstaff',
            constraint=models.UniqueConstraint(fields=('school', 'staff_id'), name='unique_staff_id_per_school'),
        ),
    ]
