# Generated by Django 5.2.8 on 2026-02-22 09:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_paymentorder_gatewaytransaction'),
        ('students', '0005_enrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeConcession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concession_type', models.CharField(choices=[('SCHOLARSHIP', 'Scholarship'), ('SIBLING', 'Sibling Discount'), ('STAFF', 'Staff Child'), ('MERIT', 'Merit Based'), ('OTHER', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateTimeField(auto_now_add=True)),
                ('reminder_type', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push Notification'), ('WHATSAPP', 'WhatsApp')], max_length=20)),
                ('sent_to', models.CharField(max_length=100)),
                ('status', models.CharField(default='SENT', max_length=20)),
                ('response_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-reminder_date'],
            },
        ),
        migrations.RemoveField(
            model_name='gatewaytransaction',
            name='order',
        ),
        migrations.RemoveField(
            model_name='paymentorder',
            name='student_fee',
        ),
        migrations.AlterModelOptions(
            name='feepayment',
            options={'ordering': ['-payment_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='feedefinition',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feepayment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='payment_status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('REFUND_PENDING', 'Refund Pending')], default='SUCCESS', max_length=20),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='due_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card'), ('NETBANKING', 'Net Banking'), ('RAZORPAY', 'Razorpay'), ('CHEQUE', 'Cheque'), ('DD', 'Demand Draft'), ('ONLINE', 'Online Transfer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PARTIAL', 'Partial'), ('UNPAID', 'Unpaid'), ('OVERDUE', 'Overdue'), ('REFUNDED', 'Refunded')], default='UNPAID', max_length=10),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['transaction_id'], name='fees_feepay_transac_7c6dca_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['razorpay_order_id'], name='fees_feepay_razorpa_3e0229_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['payment_status'], name='fees_feepay_payment_90881c_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['payment_date'], name='fees_feepay_payment_71212d_idx'),
        ),
        migrations.AddField(
            model_name='feeconcession',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feeconcession',
            name='fee_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.feedefinition'),
        ),
        migrations.AddField(
            model_name='feeconcession',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concessions', to='students.student'),
        ),
        migrations.AddField(
            model_name='feereminder',
            name='student_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='fees.studentfee'),
        ),
        migrations.DeleteModel(
            name='GatewayTransaction',
        ),
        migrations.DeleteModel(
            name='PaymentOrder',
        ),
    ]
