# Generated by Django 5.2.8 on 2026-02-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_feepayment_refunded_amount_feerefundevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
