# Generated by Django 5.2.8 on 2026-02-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_alter_feepayment_razorpay_order_id_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfee',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid'), ('OVERDUE', 'Overdue'), ('REFUNDED', 'Refunded')], default='UNPAID', max_length=10),
        ),
    ]
