# Generated by Django 5.2.8 on 2025-12-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_students', models.IntegerField(default=0)),
                ('total_staffs', models.IntegerField(default=0)),
                ('total_teachers', models.IntegerField(default=0)),
                ('total_non_teaching', models.IntegerField(default=0)),
            ],
        ),
    ]
