# Generated by Django 5.2.8 on 2026-03-26 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0002_academicyear'),
        ('staff', '0006_alter_nonteachingstaff_profile_image'),
        ('students', '0006_student_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['room__block__name', 'room__room_number', 'bed_number'],
            },
        ),
        migrations.CreateModel(
            name='HostelBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('gender_policy', models.CharField(choices=[('boys', 'Boys'), ('girls', 'Girls'), ('coed', 'Co-Ed')], default='coed', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostelAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('expected_check_out_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=120)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hostel_allocations', to='school.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_allocations', to='students.student')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='hostel.hostelbed')),
            ],
            options={
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HostelIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('occurred_at', models.DateTimeField()),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='hostel.hostelallocation')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.nonteachingstaff')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HostelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=30)),
                ('floor', models.IntegerField(default=0)),
                ('room_type', models.CharField(choices=[('standard', 'Standard'), ('ac', 'AC'), ('deluxe', 'Deluxe')], default='standard', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostel.hostelblock')),
            ],
            options={
                'ordering': ['block__name', 'floor', 'room_number'],
            },
        ),
        migrations.AddField(
            model_name='hostelbed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='hostel.hostelroom'),
        ),
        migrations.CreateModel(
            name='HostelWardenAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warden_assignments', to='hostel.hostelblock')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_warden_blocks', to='staff.nonteachingstaff')),
            ],
        ),
        migrations.CreateModel(
            name='HostelAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('out_pass', 'Out Pass'), ('leave', 'Leave'), ('absent', 'Absent')], default='present', max_length=15)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='hostel.hostelallocation')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.nonteachingstaff')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'unique_together': {('allocation', 'date')},
            },
        ),
        migrations.AddConstraint(
            model_name='hostelallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student',), name='uniq_active_hostel_allocation_per_student'),
        ),
        migrations.AddConstraint(
            model_name='hostelallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('bed',), name='uniq_active_hostel_allocation_per_bed'),
        ),
        migrations.AlterUniqueTogether(
            name='hostelroom',
            unique_together={('block', 'room_number')},
        ),
        migrations.AlterUniqueTogether(
            name='hostelbed',
            unique_together={('room', 'bed_number')},
        ),
        migrations.AddConstraint(
            model_name='hostelwardenassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('block', 'staff'), name='uniq_active_warden_per_block_staff'),
        ),
    ]
