# Generated by Django 5.2.8 on 2026-03-29 00:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
        ('staff', '0006_alter_nonteachingstaff_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelInOutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'IN'), ('out', 'OUT')], max_length=5)),
                ('moved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_out_logs', to='hostel.hostelallocation')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.nonteachingstaff')),
            ],
            options={
                'ordering': ['-moved_at', '-id'],
            },
        ),
    ]
