# Generated by Django 5.2.8 on 2026-03-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_hostelinoutlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelallocation',
            name='created_by_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='hostelattendance',
            name='created_by_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='hostelbed',
            name='created_by_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='hostelblock',
            name='created_by_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='hostelincident',
            name='created_by_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='hostelinoutlog',
            name='created_by_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='hostelroom',
            name='created_by_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='hostelwardenassignment',
            name='created_by_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
