# Generated by Django 5.2.8 on 2026-02-09 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0001_initial'),
        ('school', '0002_academicyear'),
        ('teachers', '0006_alter_teacherallocation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.academicyear'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approved_by_name',
            field=models.CharField(blank=True, help_text='Name of Admin or Teacher who approved', max_length=100),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='admin_comment',
            field=models.TextField(blank=True),
        ),
    ]
