# Generated by Django 5.2.8 on 2026-01-21 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('rank', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.AlterField(
            model_name='examtype',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='examtype',
            name='rank',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='examtype',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='exams.examterm'),
        ),
    ]
