# Generated by Django 5.2.8 on 2026-01-21 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_examterm_alter_examtype_name_alter_examtype_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtype',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='exams.examterm'),
        ),
        migrations.AlterUniqueTogether(
            name='examtype',
            unique_together={('term', 'name')},
        ),
    ]
