# Generated by Django 5.2.8 on 2026-01-24 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_examtype_term_alter_examtype_unique_together'),
        ('students', '0004_student_standard'),
        ('subjects', '0001_initial'),
        ('teachers', '0004_teacherallocation_allocated_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('new_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reason', models.TextField(default='Correction needed')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.examtype')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
            ],
        ),
    ]
