# Generated by Django 5.2.8 on 2026-01-29 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_markchangerequest'),
        ('school', '0002_academicyear'),
        ('students', '0005_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='examschedule',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='school.academicyear'),
        ),
        migrations.AddField(
            model_name='studentmark',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='students.enrollment'),
        ),
    ]
