# Generated by Django 5.2.8 on 2026-01-29 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_examschedule_academic_year_studentmark_enrollment'),
        ('school', '0002_academicyear'),
        ('students', '0005_enrollment'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentmark',
            unique_together={('enrollment', 'subject', 'exam_type')},
        ),
        migrations.AddField(
            model_name='markchangerequest',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.enrollment'),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='school.academicyear'),
        ),
        migrations.AlterField(
            model_name='markchangerequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_requests', to='students.student'),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='students.enrollment'),
        ),
        migrations.AlterUniqueTogether(
            name='examschedule',
            unique_together={('exam_type', 'academic_year')},
        ),
        migrations.RemoveField(
            model_name='studentmark',
            name='student',
        ),
    ]
