# Generated by Django 5.2.8 on 2026-01-29 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_alter_studentmark_unique_together_and_more'),
        ('students', '0005_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markchangerequest',
            name='student',
        ),
        migrations.AlterField(
            model_name='markchangerequest',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.enrollment'),
        ),
    ]
