# Generated by Django 5.2.8 on 2026-01-31 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_remove_markchangerequest_student_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examschedule',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterUniqueTogether(
            name='examschedule',
            unique_together=set(),
        ),
    ]
