# Generated by Django 5.2.8 on 2026-02-04 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_remove_section_class_teacher_classteacher'),
        ('exams', '0008_alter_examschedule_options_and_more'),
        ('school', '0002_academicyear'),
        ('students', '0005_enrollment'),
        ('subjects', '0001_initial'),
        ('teachers', '0006_alter_teacherallocation_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.academicyear')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.examterm')),
            ],
            options={
                'unique_together': {('academic_year', 'term', 'section', 'subject', 'test_name')},
            },
        ),
        migrations.CreateModel(
            name='ClassTestMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5)),
                ('class_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='exams.classtest')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.enrollment')),
            ],
            options={
                'unique_together': {('class_test', 'enrollment')},
            },
        ),
    ]
