# Generated by Django 5.2.8 on 2026-02-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_classtest_classtestmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='markchangerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
