# Generated by Django 5.2.8 on 2026-02-19 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_markchangerequest_updated_at'),
        ('school', '0002_academicyear'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentmark',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='markchangerequest',
            name='exam_type',
        ),
        migrations.AddField(
            model_name='examterm',
            name='academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exam_terms', to='school.academicyear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='markchangerequest',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exams.examschedule'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentmark',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='exams.examschedule'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examterm',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='studentmark',
            name='exam_type',
        ),
    ]
