# Generated by Django 5.2.8 on 2026-02-19 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_alter_studentmark_unique_together_and_more'),
        ('school', '0002_academicyear'),
        ('students', '0005_enrollment'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examterm',
            unique_together={('academic_year', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='studentmark',
            unique_together={('enrollment', 'subject', 'schedule')},
        ),
    ]
