# Generated by Django 5.2.8 on 2025-12-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('qualification', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=100)),
                ('address', models.TextField(default='Not Provided')),
                ('extra_details', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
