# Generated by Django 5.2.8 on 2025-12-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('teachers', '0003_teacherallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherallocation',
            name='allocated_classes',
            field=models.ManyToManyField(related_name='subject_teachers', to='academics.section'),
        ),
    ]
