# Generated by Django 5.2.8 on 2026-02-01 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('school', '0002_academicyear'),
        ('subjects', '0001_initial'),
        ('teachers', '0004_teacherallocation_allocated_classes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherallocation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='teacherallocation',
            name='academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_allocations', to='school.academicyear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherallocation',
            name='standard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.standard'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacherallocation',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
        migrations.RemoveField(
            model_name='teacherallocation',
            name='allocated_classes',
        ),
    ]
