# Generated by Django 5.2.8 on 2026-02-01 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('school', '0002_academicyear'),
        ('subjects', '0001_initial'),
        ('teachers', '0005_alter_teacherallocation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherallocation',
            unique_together={('academic_year', 'teacher', 'subject', 'standard')},
        ),
    ]
