# Generated by Django 5.2.8 on 2026-02-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_teacher_joining_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/students/'),
        ),
    ]
