# Generated by Django 5.2.8 on 2026-06-13 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_institution_alter_school_options_academicyear_school_and_more'),
        ('teachers', '0010_alter_teacher_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='school.school'),
        ),
        migrations.AddField(
            model_name='teacherallocation',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_allocations', to='school.school'),
        ),
    ]
