# Generated by Django 5.2.8 on 2026-01-09 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0002_nonteachingstaff_user_alter_nonteachingstaff_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=100)),
                ('staff_type', models.CharField(choices=[('admin_staff', 'Admin Staff'), ('finance_staff', 'Finance Staff'), ('it_staff', 'IT Staff'), ('operations_staff', 'Operations Staff'), ('transport_staff', 'Transport Staff'), ('external_staff', 'External Staff')], max_length=50)),
                ('initial_quantity', models.PositiveIntegerField(default=0)),
                ('current_quantity', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('used', 'Used / Unsealed'), ('damaged', 'Damaged / Broken'), ('restocked', 'Restocked (Admin)')], max_length=20)),
                ('quantity_changed', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='inventory.inventoryitem')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.nonteachingstaff')),
            ],
        ),
    ]
