# Generated by Django 5.2.8 on 2026-01-30 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('students', '0005_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviorreport',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_reports', to='students.enrollment'),
        ),
    ]
