# Generated by Django 5.2.8 on 2026-01-30 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_remove_markchangerequest_student_and_more'),
        ('reports', '0002_behaviorreport_enrollment'),
        ('students', '0005_enrollment'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='behaviorreport',
            unique_together={('enrollment', 'subject', 'term')},
        ),
        migrations.AlterField(
            model_name='behaviorreport',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_reports', to='students.enrollment'),
        ),
        migrations.RemoveField(
            model_name='behaviorreport',
            name='student',
        ),
    ]
