"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import os
import re

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# --------------------------------------------------------
# Environment helpers (.env + parser helpers)
# --------------------------------------------------------
def load_env_file(env_path: Path) -> None:
    """Load KEY=VALUE pairs from .env into os.environ without overriding real env vars."""
    if not env_path.exists():
        return

    for raw_line in env_path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#'):
            continue

        if line.startswith('export '):
            line = line[7:].strip()

        if '=' not in line:
            continue

        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip()

        # Strip optional matching quotes
        if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
            value = value[1:-1]

        os.environ.setdefault(key, value)


def env_bool(name: str, default: bool = False) -> bool:
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.strip().lower() in {'1', 'true', 'yes', 'on'}


def env_int(name: str, default: int) -> int:
    raw = os.getenv(name)
    if raw is None or not raw.strip():
        return default
    try:
        return int(raw)
    except (TypeError, ValueError):
        return default


def whatsapp_curl_fallback() -> dict[str, str]:
    """Read local Meta WhatsApp curl sample when env vars are not set."""
    sample_path = BASE_DIR.parent / 'xozo-tech_whatsapp_api.txt'
    if not sample_path.exists():
        return {}

    text = sample_path.read_text(encoding='utf-8', errors='ignore')
    url_match = re.search(r'graph\.facebook\.com/(v[0-9.]+)/([^/]+)/messages', text)
    token_match = re.search(r'Authorization:\s*Bearer\s+([^\'"\\\s]+)', text, re.IGNORECASE)
    template_match = re.search(r'"name"\s*:\s*"([^"]+)"', text)
    language_match = re.search(r'"code"\s*:\s*"([^"]+)"', text)

    return {
        'api_version': url_match.group(1) if url_match else '',
        'phone_number_id': url_match.group(2) if url_match else '',
        'access_token': token_match.group(1) if token_match else '',
        'template_name': template_match.group(1) if template_match else '',
        'template_language': language_match.group(1) if language_match else '',
    }


def env_list(name: str, default: list[str]) -> list[str]:
    raw = os.getenv(name)
    if raw is None or not raw.strip():
        return default
    return [item.strip() for item in raw.split(',') if item.strip()]


load_env_file(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-+#v&wca(i4y&mbi$%m97p)#y7o_4jdx^f_ssic+2g55%&5c^1=')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', True)

ALLOWED_HOSTS = env_list(
    'ALLOWED_HOSTS',
    ['*', 'http://192.168.33.71:8000', '192.168.33.71', 'http://192.168.33.71:3000'],
)


# Application definition

INSTALLED_APPS = [
    'daphne',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party apps
    'rest_framework',
    'rest_framework.authtoken',  # Required for Token Login

    # Local apps
    'accounts.apps.AccountsConfig',
    'school',
    'schooladmin',
    'teachers',
    'students',
    'staff',
    'academics',
    'attendance',
    'timetable',
    'subjects',
    'exams',
    'fees',
    'assignments',
    'reports',
    'tasks',
    'announcements',
    'performance',
    'class_resources',
    'subject_materials',
    'transport',
    'staff_work',
    'inventory',
    'leave_management',
    'holidays',
    'salary',
    'channels',
    'notifications',
    'audit',
    'meeting',
    'hostel',
    'promotions',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    # Placed here so it runs after session is loaded but before common checks
    'config.middleware.DynamicSecurityMiddleware',

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

# Redis Configuration
REDIS_HOST = os.getenv('REDIS_HOST', '127.0.0.1')
REDIS_PORT = env_int('REDIS_PORT', 6379)

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [(REDIS_HOST, REDIS_PORT)],
        },
    },
}

# # Database
# DATABASES = {
#     'default': {
#         'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.postgresql'),
#         'NAME': os.getenv('DB_NAME', 'school_db_v1'),
#         'USER': os.getenv('DB_USER', 'postgres'),
#         'PASSWORD': os.getenv('DB_PASSWORD', 'postgres'),
#         'HOST': os.getenv('DB_HOST', 'localhost'),
#         'PORT': os.getenv('DB_PORT', '5432'),
#     }
# }

DB_ENGINE = os.getenv('DB_ENGINE', 'django.db.backends.sqlite3')

if DB_ENGINE == 'django.db.backends.sqlite3':
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': os.path.join(BASE_DIR, os.getenv('DB_NAME', 'db.sqlite3')),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST'),
            'PORT': os.getenv('DB_PORT'),
        }
    }


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = os.getenv('LANGUAGE_CODE', 'en-us')
TIME_ZONE = os.getenv('TIME_ZONE', 'Asia/Kolkata')

USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'accounts.User'

# --- SECURITY SETTINGS ---
# False = Developer Mode (Postman works, Plain Text)
# True = Production Mode (App works, Encrypted)
ENABLE_ENCRYPTION = env_bool('ENABLE_ENCRYPTION', False)
OTP_REQUIRED = env_bool('OTP_REQUIRED', env_bool('otp_required', True))
MANUAL_ADMIN_OTP = os.getenv('MANUAL_ADMIN_OTP', '6258')
ADMIN_ACCESS_API_URL = os.getenv('ADMIN_ACCESS_API_URL', '').strip()
ADMIN_ACCESS_API_KEY = os.getenv('ADMIN_ACCESS_API_KEY', '').strip()
ADMIN_ACCESS_API_TIMEOUT = env_int('ADMIN_ACCESS_API_TIMEOUT', 5)
ADMIN_ACCESS_FAIL_CLOSED = env_bool('ADMIN_ACCESS_FAIL_CLOSED', True)

# WhatsApp Business Cloud API
WHATSAPP_CURL_FALLBACK = whatsapp_curl_fallback()
WHATSAPP_ALERTS_ENABLED = env_bool(
    'WHATSAPP_ALERTS_ENABLED',
    bool(WHATSAPP_CURL_FALLBACK.get('phone_number_id') and WHATSAPP_CURL_FALLBACK.get('access_token')),
)
WHATSAPP_PHONE_NUMBER_ID = os.getenv('WHATSAPP_PHONE_NUMBER_ID') or WHATSAPP_CURL_FALLBACK.get('phone_number_id', '')
WHATSAPP_ACCESS_TOKEN = os.getenv('WHATSAPP_ACCESS_TOKEN') or WHATSAPP_CURL_FALLBACK.get('access_token', '')
WHATSAPP_API_VERSION = os.getenv('WHATSAPP_API_VERSION') or WHATSAPP_CURL_FALLBACK.get('api_version') or 'v25.0'
WHATSAPP_TEMPLATE_NAME = os.getenv('WHATSAPP_TEMPLATE_NAME') or WHATSAPP_CURL_FALLBACK.get('template_name') or 'sportifo_2'
WHATSAPP_TEMPLATE_LANGUAGE = os.getenv('WHATSAPP_TEMPLATE_LANGUAGE') or WHATSAPP_CURL_FALLBACK.get('template_language') or 'en'
WHATSAPP_REQUEST_TIMEOUT = env_int('WHATSAPP_REQUEST_TIMEOUT', 10)

CORS_ALLOW_ALL_ORIGINS = env_bool('CORS_ALLOW_ALL_ORIGINS', False)

CORS_ALLOWED_ORIGINS = env_list(
    'CORS_ALLOWED_ORIGINS',
    [
        'https://school-management-rho-puce.vercel.app',
        'http://localhost:3000',
        'http://192.168.33.71:3000',
        'http://127.0.0.1:3000',
        'https://posttympanic-semipurposively-sanora.ngrok-free.dev',
        'https://lanelle-overintense-chandler.ngrok-free.dev',
    ],
)

CORS_ALLOW_CREDENTIALS = env_bool('CORS_ALLOW_CREDENTIALS', True)

# Also add CSRF trusted origins for Django
CSRF_TRUSTED_ORIGINS = env_list(
    'CSRF_TRUSTED_ORIGINS',
    [
        'https://school-management-rho-puce.vercel.app',
        'http://localhost:3000',
        'http://127.0.0.1:3000',
        'http://192.168.33.71:3000',
        'https://posttympanic-semipurposively-sanora.ngrok-free.dev',
        'https://lanelle-overintense-chandler.ngrok-free.dev',
    ],
)

CORS_ALLOW_METHODS = env_list(
    'CORS_ALLOW_METHODS',
    ['DELETE', 'GET', 'OPTIONS', 'PATCH', 'POST', 'PUT'],
)

CORS_ALLOW_HEADERS = env_list(
    'CORS_ALLOW_HEADERS',
    [
        'accept',
        'accept-encoding',
        'authorization',
        'content-type',
        'dnt',
        'origin',
        'user-agent',
        'x-csrftoken',
        'x-requested-with',
        'ngrok-skip-browser-warning',
        'x-timestamp',
        'x-admin-verified',
        'x-bulk-approval',
        'x-signature',
    ],
)


PAYMENT_GATEWAY_ENABLED = env_bool('PAYMENT_GATEWAY_ENABLED', True)

# Security Settings
BULK_PAYMENT_APPROVAL_REQUIRED = env_bool('BULK_PAYMENT_APPROVAL_REQUIRED', True)
PAYMENT_REQUEST_TIMEOUT = env_int('PAYMENT_REQUEST_TIMEOUT', 30)
MAX_BULK_PAYMENTS_PER_BATCH = env_int('MAX_BULK_PAYMENTS_PER_BATCH', 100)
PAYMENT_CLIENT_SIGNATURE_REQUIRED = env_bool('PAYMENT_CLIENT_SIGNATURE_REQUIRED', False)

# RazorpayX (Payouts) Configuration
RAZORPAYX_API_BASE = os.getenv('RAZORPAYX_API_BASE', 'https://api.razorpay.com/v1')
RAZORPAYX_KEY_ID = os.getenv('RAZORPAYX_KEY_ID', '')
RAZORPAYX_KEY_SECRET = os.getenv('RAZORPAYX_KEY_SECRET', '')
RAZORPAYX_SOURCE_ACCOUNT_NUMBER = os.getenv('RAZORPAYX_SOURCE_ACCOUNT_NUMBER', '')
RAZORPAYX_WEBHOOK_SECRET = os.getenv('RAZORPAYX_WEBHOOK_SECRET', '')

RAZORPAY_KEY_ID = os.getenv('RAZORPAY_KEY_ID', 'rzp_test_SJvqiMgxzPmpG2')
RAZORPAY_KEY_SECRET = os.getenv('RAZORPAY_KEY_SECRET', 'Z4iHDhgOkKKw453MXaSEBMYb')
RAZORPAY_WEBHOOK_SECRET = os.getenv('RAZORPAY_WEBHOOK_SECRET', 'Sivanesan@25062002')
RAZORPAY_ENABLED = env_bool('RAZORPAY_ENABLED', True)
RAZORPAY_TEST_MODE = env_bool('RAZORPAY_TEST_MODE', False)
RAZORPAY_WEBHOOK_URL = os.getenv(
    'RAZORPAY_WEBHOOK_URL',
    'https://lanelle-overintense-chandler.ngrok-free.dev/api/fees/webhook/razorpay/',
)

# Try to import local database settings (for PythonAnywhere)
try:
    from .db_settings import *
except ImportError:
    pass

# --- DRF CONFIGURATION ---
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# --- EMAIL SETTINGS (Gmail) ---
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = env_int('EMAIL_PORT', 587)
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', True)
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'sivanesan8113@gmail.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'pzmzgnrhawuclxim')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'sivanesan8113@gmail.com')
EMAIL_TIMEOUT = env_int('EMAIL_TIMEOUT', 8)
PASSWORD_RESET_DEBUG_OTP_ON_EMAIL_FAILURE = env_bool(
    'PASSWORD_RESET_DEBUG_OTP_ON_EMAIL_FAILURE',
    DEBUG,
)

# --------------------------------------------------------
# Firebase Configuration for Push Notifications
# --------------------------------------------------------
FIREBASE_ENABLED = env_bool('FIREBASE_ENABLED', False)

firebase_key_path_env = os.getenv('FIREBASE_KEY_PATH', 'firebase_credentials.json')
if os.path.isabs(firebase_key_path_env):
    FIREBASE_KEY_PATH = firebase_key_path_env
else:
    FIREBASE_KEY_PATH = os.path.join(BASE_DIR, firebase_key_path_env)

if FIREBASE_ENABLED:
    import firebase_admin
    from firebase_admin import credentials

    if not firebase_admin._apps:
        cred = credentials.Certificate(FIREBASE_KEY_PATH)
        firebase_admin.initialize_app(cred)
