# Generated by Django 5.2.8 on 2025-12-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
