# Generated by Django 5.2.8 on 2026-02-01 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignmentsubmission_description'),
        ('school', '0002_academicyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='school.academicyear'),
            preserve_default=False,
        ),
    ]
