# Generated by Django 5.2.8 on 2026-02-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_assignment_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
