# Generated by Django 5.2.8 on 2026-02-21 12:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed'), ('PASSWORD_CHANGE', 'Password Change'), ('PASSWORD_RESET', 'Password Reset'), ('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('PAYMENT_INITIATED', 'Payment Initiated'), ('PAYMENT_PROCESSED', 'Payment Processed'), ('PAYMENT_FAILED', 'Payment Failed'), ('PAYMENT_VERIFIED', 'Payment Verified'), ('BULK_PAYMENT', 'Bulk Payment'), ('BANK_TRANSFER', 'Bank Transfer'), ('BANK_TRANSFER_VERIFIED', 'Bank Transfer Verified'), ('STAFF_SALARY_CALCULATED', 'Staff Salary Calculated'), ('TEACHER_SALARY_CALCULATED', 'Teacher Salary Calculated'), ('STAFF_SALARY_PROCESSED', 'Staff Salary Processed'), ('TEACHER_SALARY_PROCESSED', 'Teacher Salary Processed'), ('STAFF_SALARY_PROCESSED_WITH_BANK', 'Staff Salary Processed with Bank'), ('TEACHER_SALARY_PROCESSED_WITH_BANK', 'Teacher Salary Processed with Bank'), ('BULK_STAFF_SALARY_PROCESSED', 'Bulk Staff Salary Processed'), ('BULK_TEACHER_SALARY_PROCESSED', 'Bulk Teacher Salary Processed'), ('SALARY_STRUCTURE_CREATED', 'Salary Structure Created'), ('SALARY_STRUCTURE_UPDATED', 'Salary Structure Updated'), ('SALARY_STRUCTURE_DELETED', 'Salary Structure Deleted'), ('PERMISSION_CHANGE', 'Permission Change'), ('ROLE_CHANGE', 'Role Change'), ('TWO_FACTOR_ENABLED', '2FA Enabled'), ('TWO_FACTOR_DISABLED', '2FA Disabled'), ('ADMIN_VERIFICATION', 'Admin Verification'), ('BULK_APPROVAL_TOKEN', 'Bulk Approval Token Generated'), ('SYSTEM_ERROR', 'System Error'), ('API_CALL', 'API Call'), ('EXPORT_DATA', 'Data Export'), ('IMPORT_DATA', 'Data Import')], max_length=50)),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical'), ('SECURITY', 'Security')], default='INFO', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('gateway_mode', models.CharField(blank=True, help_text='REAL or DUMMY mode', max_length=10)),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('browser_info', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='audit_audit_user_id_e8be02_idx'), models.Index(fields=['action', 'timestamp'], name='audit_audit_action_2a1328_idx'), models.Index(fields=['ip_address', 'timestamp'], name='audit_audit_ip_addr_4a1174_idx'), models.Index(fields=['timestamp'], name='audit_audit_timesta_19e18a_idx')],
            },
        ),
    ]
