# Generated by Django 5.2.8 on 2026-02-26 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auditlog_indexes_severity_gateway'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_severit_4d72db_idx',
            old_name='audit_audit_severit_2cc4ee_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_gateway_221c03_idx',
            old_name='audit_audit_gateway_9ab143_idx',
        ),
    ]
