# Generated by Django 5.2.8 on 2025-12-25 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('subjects', '0001_initial'),
        ('teachers', '0004_teacherallocation_allocated_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('task_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('task_type', models.CharField(choices=[('reading', 'Reading'), ('writing', 'Writing'), ('assignment', 'Assignment'), ('project', 'Project')], max_length=50)),
                ('estimated_time', models.IntegerField(help_text='Time in minutes')),
                ('teacher_note', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('important', 'Important'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
            options={
                'ordering': ['-date', 'task_number'],
                'unique_together': {('teacher', 'date', 'task_number')},
            },
        ),
    ]
