# Generated by Django 5.2.8 on 2025-12-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='priority',
            field=models.CharField(choices=[('important', 'Important'), ('normal', 'Normal'), ('urgent', 'Urgent')], default='normal', max_length=20),
        ),
    ]
