# Generated by Django 5.2.8 on 2026-02-02 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_academicyear'),
        ('tasks', '0002_alter_todotask_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='todo_tasks', to='school.academicyear'),
            preserve_default=False,
        ),
    ]
