# Generated by Django 5.2.8 on 2026-01-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_type', models.CharField(choices=[('admin_staff', 'Admin Staff'), ('finance_staff', 'Finance Staff'), ('it_staff', 'IT Staff'), ('operations_staff', 'Operations Staff'), ('transport_staff', 'Transport Staff'), ('external_staff', 'External Staff')], max_length=50, unique=True)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('late_penalty_percentage', models.FloatField(default=10.0)),
            ],
        ),
    ]
