# Generated by Django 5.2.8 on 2026-02-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(help_text='Teacher ID (e.g., TCH001)', max_length=50, unique=True)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('late_penalty_percentage', models.FloatField(default=10.0)),
            ],
        ),
    ]
