# Generated by Django 5.2.8 on 2026-02-21 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_staffsalarypayment_teachersalarypayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_payments', models.IntegerField()),
                ('successful_payments', models.IntegerField(default=0)),
                ('failed_payments', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('partially_completed', 'Partially Completed')], default='processing', max_length=20)),
                ('results', models.JSONField()),
                ('bank_code', models.CharField(default='DEFAULT', max_length=20)),
                ('gateway_mode', models.CharField(default='DUMMY', help_text='REAL or DUMMY mode', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_batches_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VIEW', 'View'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('PAYMENT_PROCESSED', 'Payment Processed'), ('BANK_TRANSFER', 'Bank Transfer'), ('BULK_OPERATION', 'Bulk Operation'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout')], max_length=50)),
                ('details', models.JSONField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='salary_audi_user_id_9a831b_idx'), models.Index(fields=['action', 'timestamp'], name='salary_audi_action_7c1994_idx')],
            },
        ),
    ]
