# Generated by Django 5.2.8 on 2026-02-21 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0004_paymentbatch_auditlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
