# Generated by Django 5.2.8 on 2026-02-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0005_delete_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffsalarypayment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='teachersalarypayment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
