# Generated by Django 5.2.8 on 2025-12-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='announcement',
            name='announcement_number',
            field=models.IntegerField(default=1),
        ),
    ]
