# Generated by Django 5.2.8 on 2026-01-07 08:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_commonannouncement_staffannouncement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonannouncement',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='staffannouncement',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
