# Generated by Django 5.2.8 on 2026-02-02 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_alter_commonannouncement_date_and_more'),
        ('school', '0002_academicyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_announcements', to='school.academicyear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commonannouncement',
            name='academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='common_announcements', to='school.academicyear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffannouncement',
            name='academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='staff_announcements', to='school.academicyear'),
            preserve_default=False,
        ),
    ]
