# Generated by Django 5.2.8 on 2026-02-03 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_announcement_academic_year_and_more'),
        ('school', '0002_academicyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('visibility', models.CharField(choices=[('ALL_TEACHERS', 'All Teachers'), ('ROLE_SPECIFIC', 'Role Specific')], default='ALL_TEACHERS', max_length=20)),
                ('target_role', models.CharField(blank=True, choices=[('CLASS_TEACHER', 'Class Teacher'), ('SUBJECT_TEACHER', 'Subject Teacher')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_announcements', to='school.academicyear')),
            ],
        ),
    ]
