# Generated by Django 5.2.8 on 2026-02-01 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_remove_section_class_teacher_classteacher'),
        ('school', '0002_academicyear'),
        ('subjects', '0001_initial'),
        ('teachers', '0006_alter_teacherallocation_unique_together'),
        ('timetable', '0002_substitution'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableslot',
            name='academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='school.academicyear'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='timetableslot',
            constraint=models.UniqueConstraint(fields=('academic_year', 'section', 'day', 'period_no'), name='unique_section_slot_per_year'),
        ),
        migrations.AddConstraint(
            model_name='timetableslot',
            constraint=models.UniqueConstraint(condition=models.Q(('teacher__isnull', False)), fields=('academic_year', 'teacher', 'day', 'period_no'), name='unique_teacher_slot_per_year'),
        ),
    ]
