# Generated by Django 5.2.8 on 2026-02-17 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_remove_section_class_teacher_classteacher'),
        ('school', '0002_academicyear'),
        ('timetable', '0003_timetableslot_academic_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.academicyear')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='academics.standard')),
            ],
            options={
                'ordering': ['start_time'],
                'constraints': [models.UniqueConstraint(fields=('academic_year', 'standard', 'name'), name='unique_break_name_per_class')],
            },
        ),
    ]
