# Generated by Django 5.2.8 on 2026-01-08 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0002_nonteachingstaff_user_alter_nonteachingstaff_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('staff_type', models.CharField(choices=[('admin_staff', 'Admin Staff'), ('finance_staff', 'Finance Staff'), ('it_staff', 'IT Staff'), ('operations_staff', 'Operations Staff'), ('transport_staff', 'Transport Staff'), ('external_staff', 'External Staff')], max_length=50)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='staff_work_proofs/%Y/%m/%d/')),
                ('completion_note', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_works', to='staff.nonteachingstaff')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='staff_work.workorder')),
            ],
            options={
                'unique_together': {('work_order', 'staff')},
            },
        ),
    ]
