# Generated by Django 5.2.8 on 2026-01-09 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_nonteachingstaff_user_alter_nonteachingstaff_role'),
        ('staff_work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RecurringTaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=15)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.nonteachingstaff')),
            ],
            options={
                'unique_together': {('staff', 'day_of_week', 'description')},
            },
        ),
    ]
