# Generated by Django 5.2.8 on 2026-02-09 09:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_work', '0002_workorder_is_recurring_recurringtasktemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
