# Generated by Django 5.2.8 on 2026-06-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_school_scoped_academics'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('standard', 'subject_code'), name='unique_subject_code_per_standard'),
        ),
    ]
