# Generated by Django 5.2.8 on 2026-03-22 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0006_student_profile_image'),
        ('teachers', '0010_alter_teacher_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMeetingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('preferred_start', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RESCHEDULE_PROPOSED', 'Reschedule Proposed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=25)),
                ('admin_note', models.TextField(blank=True)),
                ('final_start', models.DateTimeField(blank=True, null=True)),
                ('final_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_meeting_requests_received', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_meeting_requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('mode', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], default='OFFLINE', max_length=10)),
                ('meeting_link', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('CONFIRMED', 'Confirmed'), ('RESCHEDULE_REQUESTED', 'Reschedule Requested'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='REQUESTED', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_meetings_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_meetings', to='students.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='teachers.teacher')),
            ],
            options={
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_type', models.CharField(choices=[('ADMIN_REQUEST', 'Admin Request'), ('TEACHER_MEETING', 'Teacher Meeting')], max_length=20)),
                ('remind_at', models.DateTimeField()),
                ('channel', models.CharField(choices=[('IN_APP', 'In App'), ('EMAIL', 'Email'), ('SMS', 'SMS')], default='IN_APP', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='meeting.adminmeetingrequest')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_reminders', to=settings.AUTH_USER_MODEL)),
                ('teacher_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='meeting.teachermeeting')),
            ],
            options={
                'ordering': ['remind_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherMeetingResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(choices=[('STUDENT', 'Student'), ('PARENT', 'Parent')], max_length=10)),
                ('response', models.CharField(choices=[('ACCEPT', 'Accept'), ('DECLINE', 'Decline'), ('RESCHEDULE', 'Reschedule')], max_length=12)),
                ('comment', models.TextField(blank=True)),
                ('proposed_start', models.DateTimeField(blank=True, null=True)),
                ('proposed_end', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='meeting.teachermeeting')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_responses', to='students.student')),
            ],
            options={
                'ordering': ['-responded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='adminmeetingrequest',
            index=models.Index(fields=['admin', 'status'], name='meeting_adm_admin_i_e7d692_idx'),
        ),
        migrations.AddIndex(
            model_name='adminmeetingrequest',
            index=models.Index(fields=['requester', 'status'], name='meeting_adm_request_282136_idx'),
        ),
        migrations.AddIndex(
            model_name='teachermeeting',
            index=models.Index(fields=['teacher', 'status'], name='meeting_tea_teacher_2f98c4_idx'),
        ),
        migrations.AddIndex(
            model_name='teachermeeting',
            index=models.Index(fields=['student', 'status'], name='meeting_tea_student_66d449_idx'),
        ),
        migrations.AddIndex(
            model_name='teachermeeting',
            index=models.Index(fields=['start_at'], name='meeting_tea_start_a_bdfa69_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingreminder',
            index=models.Index(fields=['status', 'remind_at'], name='meeting_mee_status_b3a954_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingreminder',
            index=models.Index(fields=['recipient', 'status'], name='meeting_mee_recipie_ad0abc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teachermeetingresponse',
            unique_together={('meeting', 'actor_type')},
        ),
    ]
