# Generated by Django 5.2.8 on 2026-02-03 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_resources', '0001_initial'),
        ('school', '0002_academicyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='classresource',
            name='academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='class_resources', to='school.academicyear'),
            preserve_default=False,
        ),
    ]
