# Generated by Django 5.2.8 on 2026-02-01 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('school', '0002_academicyear'),
        ('teachers', '0006_alter_teacherallocation_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='class_teacher',
        ),
        migrations.CreateModel(
            name='ClassTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.academicyear')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.section')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher_of', to='teachers.teacher')),
            ],
            options={
                'unique_together': {('academic_year', 'section'), ('academic_year', 'teacher')},
            },
        ),
    ]
