# Generated by Django 5.2.8 on 2026-06-13 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_remove_section_class_teacher_classteacher'),
        ('school', '0003_institution_alter_school_options_academicyear_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classteacher',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_teachers', to='school.school'),
        ),
        migrations.AddField(
            model_name='section',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='school.school'),
        ),
        migrations.AddField(
            model_name='standard',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standards', to='school.school'),
        ),
    ]
