# Generated by Django 5.2.8 on 2026-06-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_classteacher_school_section_school_standard_school'),
        ('school', '0006_school_scoped_academics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AddConstraint(
            model_name='standard',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_standard_per_school'),
        ),
    ]
