# Generated by Django 5.2.8 on 2026-01-11 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_nonteachingstaff_user_alter_nonteachingstaff_role'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='current_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='current_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='current_speed',
            field=models.FloatField(blank=True, help_text='Speed in km/h', null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='route',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='driver',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'transport_staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bus', to='staff.nonteachingstaff'),
        ),
    ]
