# Generated by Django 5.2.8 on 2026-01-12 13:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_nonteachingstaff_user_alter_nonteachingstaff_role'),
        ('transport', '0002_route_current_latitude_route_current_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('trip_type', models.CharField(choices=[('Morning', 'Morning Pickup'), ('Evening', 'Evening Drop')], default='Morning', max_length=10)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Absent', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='transport.transportallocation')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.nonteachingstaff')),
            ],
            options={
                'unique_together': {('allocation', 'date', 'trip_type')},
            },
        ),
    ]
