# Generated by Django 5.2.8 on 2026-02-11 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_nonteachingstaff_user_alter_nonteachingstaff_role'),
        ('transport', '0003_transportattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportExpenseProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('proof_file', models.FileField(upload_to='transport_proofs/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_expenses', to='staff.nonteachingstaff')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='transport.vehicle')),
            ],
        ),
    ]
