# Generated by Django 5.2.8 on 2026-02-12 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_transportexpenseproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportallocation',
            name='allocated_at',
            field=models.DateField(auto_now_add=True, default=datetime.date(2025, 12, 15)),
            preserve_default=False,
        ),
    ]
