# Generated by Django 5.2.8 on 2026-03-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_transportallocation_allocated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportallocation',
            name='stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='allocations', to='transport.stop'),
        ),
    ]
