# Generated by Codex on 2026-06-05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_transportallocation_stop'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportArrivalAlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_date', models.DateField(default=django.utils.timezone.localdate)),
                ('threshold_km', models.FloatField(default=1.0)),
                ('distance_km', models.FloatField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_alert_logs', to='transport.transportallocation')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_alert_logs', to='transport.route')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_alert_logs', to='transport.stop')),
            ],
            options={
                'ordering': ['-sent_at'],
                'unique_together': {('allocation', 'route', 'stop', 'alert_date', 'threshold_km')},
            },
        ),
    ]
