# Generated by Codex on 2026-06-06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_route_trip_locations_stop_trip_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportWhatsAppAlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('bus_started', 'Bus started'), ('near_stop', 'Near stop')], max_length=20)),
                ('trip_type', models.CharField(choices=[('Morning', 'Morning Pickup'), ('Evening', 'Evening Drop')], default='Morning', max_length=10)),
                ('alert_date', models.DateField(default=django.utils.timezone.localdate)),
                ('sent_to', models.CharField(max_length=30)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_alert_logs', to='transport.transportallocation')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_alert_logs', to='transport.route')),
                ('stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_alert_logs', to='transport.stop')),
            ],
            options={
                'ordering': ['-sent_at'],
                'unique_together': {('allocation', 'route', 'stop', 'alert_type', 'trip_type', 'alert_date')},
            },
        ),
    ]
