# Generated by Codex on 2026-06-05

from django.db import migrations, models


def seed_whatsapp_alert_settings(apps, schema_editor):
    WhatsAppAlertSetting = apps.get_model('notifications', 'WhatsAppAlertSetting')
    for alert_type in ['fees', 'meetings', 'assignments', 'leave', 'exams', 'transport']:
        WhatsAppAlertSetting.objects.get_or_create(
            alert_type=alert_type,
            defaults={'enabled': True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_fcmdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppAlertSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('fees', 'Fee reminders'), ('meetings', 'Meeting alerts'), ('assignments', 'Assignment alerts'), ('leave', 'Leave alerts'), ('exams', 'Exam and mark-change alerts'), ('transport', 'Transport alerts')], max_length=30, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['alert_type'],
            },
        ),
        migrations.RunPython(seed_whatsapp_alert_settings, migrations.RunPython.noop),
    ]
