# Generated by Codex on 2026-06-06

from django.db import migrations, models


def seed_attendance_whatsapp_alert(apps, schema_editor):
    WhatsAppAlertSetting = apps.get_model('notifications', 'WhatsAppAlertSetting')
    WhatsAppAlertSetting.objects.get_or_create(
        alert_type='attendance',
        defaults={'enabled': True},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_whatsappalertsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappalertsetting',
            name='alert_type',
            field=models.CharField(
                choices=[
                    ('fees', 'Fee reminders'),
                    ('meetings', 'Meeting alerts'),
                    ('assignments', 'Assignment alerts'),
                    ('leave', 'Leave alerts'),
                    ('exams', 'Exam and mark-change alerts'),
                    ('transport', 'Transport alerts'),
                    ('attendance', 'Attendance alerts'),
                ],
                max_length=30,
                unique=True,
            ),
        ),
        migrations.RunPython(seed_attendance_whatsapp_alert, migrations.RunPython.noop),
    ]
