# Generated by Django 5.2.8 on 2026-01-06 11:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('staff', '0002_nonteachingstaff_user_alter_nonteachingstaff_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('check_in_time', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(default='Present', max_length=20)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='staff.nonteachingstaff')),
            ],
            options={
                'verbose_name_plural': 'Staff Attendance',
                'unique_together': {('staff', 'date')},
            },
        ),
    ]
