# Generated by Django 5.2.8 on 2026-01-28 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_options_and_more'),
        ('students', '0005_enrollment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', 'enrollment__student__student_name']},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('enrollment', 'date')},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.enrollment'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late')], default='Present', max_length=15),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='section',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='standard',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
    ]
