# Generated by Django 5.2.8 on 2026-02-07 09:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendance_options_and_more'),
        ('teachers', '0006_alter_teacherallocation_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('school_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('allowed_radius_meters', models.IntegerField(default=200)),
                ('late_cutoff_time', models.TimeField(default='09:00:00')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('check_in_time', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(default='Present', max_length=20)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='teachers.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'date')},
            },
        ),
    ]
