# Generated by Django 5.2.8 on 2026-03-23 11:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendanceconfig_teacherattendance'),
        ('staff', '0006_alter_nonteachingstaff_profile_image'),
        ('teachers', '0010_alter_teacher_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRAttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_scope', models.CharField(choices=[('teacher', 'Teacher'), ('staff', 'Staff'), ('both', 'Both')], default='both', max_length=10)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField()),
                ('rotation_seconds', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_attendance_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QRAttendanceScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_slot', models.PositiveIntegerField()),
                ('accepted', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('marked_status', models.CharField(blank=True, max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scan_logs', to='staff.nonteachingstaff')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scan_logs', to='teachers.teacher')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_attendance_scan_logs', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='attendance.qrattendancesession')),
            ],
            options={
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['session', 'accepted'], name='attendance__session_dad788_idx'), models.Index(fields=['teacher', 'session'], name='attendance__teacher_b028e2_idx'), models.Index(fields=['staff', 'session'], name='attendance__staff_i_a036cd_idx')],
            },
        ),
    ]
